### ISSUE TITLE
License of use should be explained.

### ISSUE THREAD

**Issue by Ranoller** [sanja-sa/gddragonbones#11]
This module remove the explicit MIT license of the readme. By default code that doesn´t have license is copyrighted with no permission of use. If it´s the case it will be good to know. If not, it will be good to know what kind of license it has.

**Comment by sanja-sa** [comment]
It's no restriction of use. I dont know, which type of license for this module I can add.

**Comment by Ranoller** [comment]
Ok, i read your edit. If is no restriction of use, if it´s free of charge and allow modifications and derivative comercial works MIT license it´s fine. This license allow any use by including your original license in any place of the derivative work. If you want to keep any restriction about use any CC license it´s fine

**Comment by sanja-sa** [comment]
Sometimes, I don't understand, why "two strings" of code must have license. This is only little plugin. For me it's not important which type of license this module must have. You can use it everywere, if you want. I'll add license file sometime later (MIT is suitable, I think).

**Comment by Ranoller** [comment]
It´s about intellectual property rights. It will be "two string of code", but are yours, this is the law in a lot of countries in the world. And no serious developer will break any copyright of code because the implications of this "act" can have in their work. There are countries that don´t have this law, but some big markets (EU, Europe, Japan, etc...) has, and judges are severe about intellectual property.

**Comment by Ranoller** [comment]
https://help.github.com/articles/adding-a-license-to-a-repository/

**Comment by blurymind** [comment]
@sanja-sa Thank you! You have much more than two strings of code here. :) What you achieved deserves more credit

@Ranoller we can close this now?

**Comment by Ranoller** [comment]
Of course there are much more than two lines of code, there are the best module that godot have by large and the most useful... Thanks sanja-sa, i close this.

**Comment by sanja-sa** [comment]
@Ranoller Maybe it's better Unlicense license?

**Comment by Ranoller** [comment]
It's not... At least it will indicate exention of reponsabilities... Law sometimes it's weird!

**Comment by blurymind** [comment]
I am quite impressed by @sanja-sa 's humility :) 
While I understand the feeling, I must agree with @Ranoller  that some developers will not use this module in their projects unless it has the license file. If the developers work for an indie company, they wouldn't be allowed to use it without the license file being included due to company policies.

That said, the MIT license which @sanja-sa chose is an excellent and will allow the module to be used in any games and by any companies
