### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by ndee85** [sanja-sa/gddragonbones#13]
Hi,
I was very excited to hear that godot now has a dragonbones module. I am developing cutout animation tools for blender and did write a dragonbones exporter module for my addon. I have rewritten the core of my exporter and it now supports the data version 5.5 of dragonbones json file.

I would love to test and see if everything is working within godot but I cannot compile. I tried all version. Current Master, 2.1.x and 3.0. Nothing works. Normal compilation without the module works. But not with the module. I get this error message:

> [Initial build] Compiling ==> modules/gddragonbones/gddragonbones.cpp
In file included from /usr/include/c++/5/cstdint:35:0,
                 from modules/gddragonbones/src/dragonBones/core/DragonBones.h:27,
                 from modules/gddragonbones/src/dragonBones/DragonBonesHeaders.h:27,
                 from modules/gddragonbones/src/GDFactory.h:7,
                 from modules/gddragonbones/gddragonbones.h:5,
                 from modules/gddragonbones/gddragonbones.cpp:1:
/usr/include/c++/5/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support \
  ^
In file included from modules/gddragonbones/src/GDFactory.h:9:0,
                 from modules/gddragonbones/gddragonbones.h:5,
                 from modules/gddragonbones/gddragonbones.cpp:1:
modules/gddragonbones/src/GDArmatureDisplay.h:4:44: fatal error: dragonBones\DragonBonesHeaders.h: No such file or directory
compilation terminated.
scons: *** [modules/gddragonbones/gddragonbones.x11.tools.64.o] Error 1
scons: building terminated because of errors.

**Comment by Ranoller** [comment]
Are you compiling with mvsc?

**Comment by ndee85** [comment]
no, I am using scons. Trying to compile under linux.

**Comment by Ranoller** [comment]
Edit: try first Sanja-sa solution, it looks well and if works it can be commited (I can´t test, don´t have linux)

(Yes, in mvsc it use scons too, i ask for the compiler... In linux obiously the compiler is not microsoft visual... All the test that we are doing for now was in visual studio. It seems that this module needs c++11 compatible compiler and by default mvsc include necesary files. Godot uses older c++ version so probably linux compiler (wharever it was in this case) read   scons-python config file and don't include c++11 needed files, i think this can be the problem... Error menssage talks about add -std=c++11 or -std=gnu++ so, can you try to compile with:  "scons platform=linux target=release_debug tools=yes std=c++11"?)

**Comment by Ranoller** [comment]
Platform is not x11... Sorry, keyword is platform=linux? (Don't remember, writing scons without parameters shows instaled platforms)

**Comment by sanja-sa** [comment]
@ndee85 Can you try change string in SCsub:
```
if (env['platform'] == 'android' or env['platform'] == 'linux'):
	env_modules.Append(CXXFLAGS=['-std=c++11'])
```

**Comment by ndee85** [comment]
@Ranoller @sanja-sa 
thanks. I will take a more detailed look at home.

**Comment by Ranoller** [comment]
It works?

**Comment by Ranoller** [comment]
So... @ndee85, This was fixed?

**Comment by ndee85** [comment]
Sorry for not responding. I got it working under windows. I will try it tonight if it works on linux and report back.

**Comment by ndee85** [comment]
Hey.. I was just trying a bit more with compiling the dragonbones module for linux. So this was my compile command:
`scons platform=x11`
I modified the SCsub like that:
`if (env['platform'] == 'android' or env['platform'] == 'x11'):
	env_modules.Append(CXXFLAGS=['-std=c++11'])`
I used x11 instead of linux. But I tried both. linux and x11. None seems to work. Here are the error messages:

For x11 set in SCsub
`scons: Reading SConscript files ...
Enabling ALSA
Enabling PulseAudio
YASM is necessary for WebM SIMD optimizations.
WebM SIMD optimizations are disabled. Check if your CPU architecture, CPU bits or platform are supported!
Checking for C header file mntent.h... (cached) yes
scons: done reading SConscript files.
scons: Building targets ...
[  7%] Compiling ==> modules/register_module_types.gen.cpp
[ 20%] Compiling ==> modules/gddragonbones/gddragonbones.cpp
In file included from modules/gddragonbones/src/GDFactory.h:9:0,
                 from modules/gddragonbones/gddragonbones.h:5,
                 from modules/gddragonbones/gddragonbones.cpp:1:
modules/gddragonbones/src/GDArmatureDisplay.h:4:44: fatal error: dragonBones\DragonBonesHeaders.h: No such file or directory
compilation terminated.
scons: *** [modules/gddragonbones/gddragonbones.x11.tools.64.o] Error 1
scons: building terminated because of errors.`

And this was the error message for linux SCsub:
`scons: Reading SConscript files ...
Enabling ALSA
Enabling PulseAudio
YASM is necessary for WebM SIMD optimizations.
WebM SIMD optimizations are disabled. Check if your CPU architecture, CPU bits or platform are supported!
Checking for C header file mntent.h... (cached) yes
scons: done reading SConscript files.
scons: Building targets ...
[ 20%] Compiling ==> modules/gddragonbones/gddragonbones.cpp
In file included from /usr/include/c++/5/cstdint:35:0,
                 from modules/gddragonbones/src/dragonBones/core/DragonBones.h:27,
                 from modules/gddragonbones/src/dragonBones/DragonBonesHeaders.h:27,
                 from modules/gddragonbones/src/GDFactory.h:7,
                 from modules/gddragonbones/gddragonbones.h:5,
                 from modules/gddragonbones/gddragonbones.cpp:1:
/usr/include/c++/5/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support \
  ^
In file included from modules/gddragonbones/src/GDFactory.h:9:0,
                 from modules/gddragonbones/gddragonbones.h:5,
                 from modules/gddragonbones/gddragonbones.cpp:1:
modules/gddragonbones/src/GDArmatureDisplay.h:4:44: fatal error: dragonBones\DragonBonesHeaders.h: No such file or directory
compilation terminated.
scons: *** [modules/gddragonbones/gddragonbones.x11.tools.64.o] Error 1
scons: building terminated because of errors.
`

**Comment by ndee85** [comment]
Btw. I have now a working exporter prototype for my coa tools. I could export all animations done in blender easily to godots drangonbones module(under windows). Thats pretty amazing to have free form deformations in godot. So thanks for the nice module.

**Comment by Ranoller** [comment]
Ou.... trouble.

Idea 1: You can try to replace -std=c++11 by -std=gnu++11 in SCub

Idea 2: If you are compilig with GCC probably need GCC 4.8.1 or up: 
https://gcc.gnu.org/projects/cxx-status.html#cxx11
(Until install check if godot needs another version, or incompatibilities, i know that linux is very sensitive to this things)

Googling that (don´t know linux) find that you can check compiler with:
$ whereis gcc
$ which gcc
$ gcc --version

I think that this request is by the dragonbones runtime, nothing to do with the module. Godot doesn´t need c++11, dragonbones yes.  But @sanja-sa is the engineer, it can have more idea about this.

**Comment by sanja-sa** [comment]
Thanks, @ndee85. Maybe it my mistake, Can you go to file GDArmatureDisplay.h and change:
`#include "dragonBones\DragonBonesHeaders.h"` => `#include "dragonBones/DragonBonesHeaders.h"`
It's correct error for x11.
For Linux: @Ranoller is right. You can check gcc version at first. 

From this error string: `/usr/include/c++/5/bits/c++0x_warning.h` @ndee85, you are still using c++0x.

You can try change in SCub:
```
if (env['platform'] == 'android' or env['platform'] == 'linux'):
 env_modules.Append(CXXFLAGS=['-std=c++11'])
```
to
`env_modules.Append(CXXFLAGS=['-std=c++11'])`
or
`env_modules.Append(CXXFLAGS=['-std=gnu++11'])`

**Comment by ndee85** [comment]
@sanja-sa 
awesome! `#include "dragonBones/DragonBonesHeaders.h"` did the trick. Now compilation works without any problem on linux!
Thanks a bunch for your time! Really happy this works now.

**Comment by ndee85** [comment]
Closing this issue.
