### ISSUE TITLE
Dragonbones object not released in game quit

### ISSUE THREAD

**Issue by Ranoller** [sanja-sa/gddragonbones#15]
Dragonbones module, in Godot 3 app exit doesn´t release memory (or at least in the correct way). 
I test with and without module to confirm that is not other node.

Issue is:
If I haven´t dragonbones node in app, on exit there is not error.
If I have dragonbones node, consoles shows on quit this:

WARNING: ObjectDB::cleanup: ObjectDB Instances still exist!
          At: core\object.cpp:1989

It is not particularly serious, but something is happend.

**Comment by sanja-sa** [comment]
@Ranoller I have the same error without using dragonbones nodes in scene, it's present when you use preview current scene and then close it when some hardy process on scene present.

**Comment by Ranoller** [comment]
Oh well... i will investigate why this happend and if i find cause report in godot github. Thanks man.
