### ISSUE TITLE
Recent change in Godot CodeBase make plugin not compile

### ISSUE THREAD

**Issue by Ranoller** [sanja-sa/gddragonbones#18]
In this commit: https://github.com/godotengine/godot/commit/b3e4bc562c07142d48907278f9cc496791ff7b33
Reduz introduces new parameters in VS:canvas_item_add_triangle_array:

OLD (servers/visual_server.h):
virtual void canvas_item_add_triangle_array(RID p_item, const Vector<int> &p_indices, const Vector<Point2> &p_points, const Vector<Color> &p_colors, const Vector<Point2> &p_uvs = Vector<Point2>(), RID p_texture = RID(), int p_count = -1, RID p_normal_map = RID()) = 0;

NEW (servers/visual_server.h):
virtual void canvas_item_add_triangle_array(RID p_item, const Vector<int> &p_indices, const Vector<Point2> &p_points, const Vector<Color> &p_colors, const Vector<Point2> &p_uvs = Vector<Point2>(), const Vector<int> &p_bones = Vector<int>(), const Vector<float> &p_weights = Vector<float>(), RID p_texture = RID(), int p_count = -1, RID p_normal_map = RID()) = 0;

Plugins fails at compiletime in line 49 in GDMesh.h because this change.
So compatibility between Godot 3.0 and Godot 3.1 for this method is breaked. (Cannot convert argument 6 from RID to const Vector <int>)
https://github.com/sanja-sa/gddragonbones/blob/master/gddragonbones/src/GDMesh.h

Probably other changes of this commit can be break other part´s of compilation. So if this module will be compatible with godot 3.1 there is needed the same change that was did adding "#if (VERSION_MAJOR == 3)" but with minor version of godot. 

King regards.

**Comment by sanja-sa** [comment]
24b24aa5ded3e4c8bcef35ffb31ddd5a0277f11c

**Comment by sanja-sa** [comment]
@Ranoller, maybe it's is better to use [2D Skeletal Deform Godot]( https://godotengine.org/article/godot-gets-2d-skeletal-deform)? But it's only for Godot ver 3.1.

**Comment by Ranoller** [comment]
I´m testing that, it´s not fully implemented. The beginning of this feature is very promising, right now it´s not comparable with dragon bones / spine editor nor runtimes, but i think that reduz´s idea is to do something similar... so probably in near future will be better to use only godot editor, or to do a direct importer to Texture -> Mesh2D  , Animation -> AnimationPlayer, bones -> Skeleton2D or something like this (probably this will be acomplished directly by gdscript or gdnative plugin). To early for now, i will continue using for a time your excellent module. Thanks for the update!
