### ISSUE TITLE
When I compiled an application, the gddragonbones was not worked.

### ISSUE THREAD

**Issue by pokemonchw** [sanja-sa/gddragonbones#21]
`ERROR: _load: No loader found for resource: res://Image/scene_dandelion/dandelion_ske.json
   At: core/io/resource_loader.cpp:186.
ERROR: poll: res://Map/Map0.tscn:7 - Parse Error: [ext_resource] referenced nonexistent resource at: res://Image/scene_dandelion/dandelion_ske.json
   At: scene/resources/scene_format_text.cpp:439.
ERROR: load: Condition ' err != OK ' is true. returned: RES()
   At: core/io/resource_loader.cpp:149.
ERROR: _load: Failed loading resource: res://Map/Map0.tscn
   At: core/io/resource_loader.cpp:186.`

**Comment by sanja-sa** [comment]
Check, that you have resource "res://Image/scene_dandelion/dandelion_ske.json" in your project, maybe "Image" must be "image" or something else in res path.

**Comment by pokemonchw** [comment]
I checked the document. It seems that I need to compile an export template separately.
