### ISSUE TITLE
Enquiry/Feature Request: Ability to find out the current frame of animation at runtime.

### ISSUE THREAD

**Issue by definite-d** [sanja-sa/gddragonbones#25]
Hello @sanja-sa!

I think the title says it all. My team's current Godot project (a combat Game) requires the values of the current frame, for hit/hurtbox manipulation. I may be wrong, but I haven't found any way to obtain that.

**Comment by Ranoller** [comment]
I don´t find any concept similar to "current frame" in dragon bones runtime. Dragon bones animation has keyframes and animate "on the fly" between them..... if you slow them... that "abstracted frame" that you talk moves to other point... so you need to work in "time" not frames... but i don´t understand why you need that, if you do an animation with a dragonbones node inside, you can animate the "hurtbox" to follow that animation.

**Comment by definite-d** [comment]
Thanks, @Ranoller!

That's quite a good idea! Can't believe I couldn't have figured that out!

**Comment by definite-d** [comment]
Hi!

This may not be the right place to put this, but heck, I found no other befitting place. The thing has to do with the fact that I found 2.5 ways to save a file in DragonBones without logging in. I think other DB users will be glad to know, right @blurymind?

Anyway, two of these methods have been mixed to form one solid skip-login save method:

To start a new project:

   Anytime you begin a new DB project, DB 'saves' it to your HDD instantly, but in a temp file in some obscure location. Access this location by hovering over the tab of the project, and clicking the location that appears below. Simply copy the file from there and paste anywhere of your choice. Now forget about the temp folder's project and open your local one. The temp file clears automatically, but it can't touch the copied project.

   Now, do some radical work on that project that would drive you crazy if it got lost from failure to save. Done? Good. Pull out a guide from the rulers, horizontally or vertically; it doesn't matter.

   Now check for the * that sits beside the name of an unsaved project. Is it gone? Yes. Work saved. No login. Easy as that. Plus, moving the guides or removing them also saves your work.

   Seems like Egret Technologies dropped the ball here, specifically v5.6.0.0003. Well, don't tell them so they don't patch it up. It's to our benefit.

   You may be wondering what the 0.5th method is. It's simply the Fatal Error, clear cache thing. Once it happens, DB saves all projects, ready for you to exit when you don't want to. Or you can just press Escape to close the error popup.

**Comment by Ranoller** [comment]
Recomended version 4.9.5 (From that version start the obscure chinese manipulation) but is good info to have here.
So, is not possible jet to "login" in 5.6? Well i have this version working...

**Comment by definite-d** [comment]
Hello again!

@Ranoller I can login quite well in version 5.6; I have to login in order to Export, as I haven't found any workarounds to that. Also, I haven't found any obscure Chinese in the GUI; even their login errors are in English. The login also works fine, all from within the app.

**Comment by blurymind** [comment]
yes it would be best to keep 4.9.5 compatibility. These login requirements are quite awful :)
