### ISSUE TITLE
Export templates for 3.2.dev?

### ISSUE THREAD

**Issue by AlexNight1986** [sanja-sa/gddragonbones#27]
hello i already be able to compile godot  with dragonbones module for Windows ,but when i try to export to Windows Desktop it ask me export templates  for "3.2.dev" wich i cannot find

**Comment by Ranoller** [comment]
you need to compile templates the same that you compile engine. release_debug and tools no and release and tools no.

**Comment by AlexNight1986** [comment]
thanks for the answer! didnt know that, could you recommend me a guide for compile the templates?
sorry i love this plugin but im a noob with compiling things

**Comment by Ranoller** [comment]
Godot with editor:
scons platform=windows target=release_debug tools=yes
Export template with debug:
scons platform=windows target=release_debug tools=no
Export template for release:
scons platform=windows target=release tools=no

after compile, executables can be finded in bin/ folder on the repository

**Comment by Ranoller** [comment]
https://docs.godotengine.org/en/3.1/development/compiling/compiling_for_windows.html

**Comment by AlexNight1986** [comment]
thank you!

**Comment by joaoluizn** [comment]
Is it possible to create an export template to windows, while being on a Linux computer? So... I'm trying to do this... and getting something like... 
![image](https://user-images.githubusercontent.com/32312434/60316652-d7906800-9941-11e9-9348-02f3eb8ecfd9.png)

Some help would be nice! Thanks!

**Comment by Ranoller** [comment]
https://docs.godotengine.org/en/3.1/development/compiling/compiling_for_windows.html

At the end there is a tutorial
