### ISSUE TITLE
Can't compile for godot 3.2 dev

### ISSUE THREAD

**Issue by kzerot** [sanja-sa/gddragonbones#30]
Hi! Trying to compile for godot 3.2 (git version)
Have an error

scons: *** [modules/gddragonbones/gddragonbones.x11.opt.debug.64.o] Error 1
In file included from modules/gddragonbones/src/GDArmatureDisplay.h:5,
                 from modules/gddragonbones/src/GDArmatureDisplay.cpp:1:
modules/gddragonbones/src/GDDisplay.h:7:10: fatal error: version_generated.gen.h: No such file or directory
    7 | #include <version_generated.gen.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by Ranoller** [comment]
https://github.com/Ranoller/gddragonbones

**Comment by kzerot** [comment]
Ranoller version seems working
