### ISSUE TITLE
FORKS OF GODOT-DRAGON BONES: please read _before_ make an issue

### ISSUE THREAD

**Issue by Ranoller** [sanja-sa/gddragonbones#33]
Forks:

To compile with godot 2.0 to 3.0 use the original repo: https://github.com/sanja-sa/gddragonbones ( needed to compile 2.0 ) (You are here!)
To compile with godot 3.1 to 4.0 before vulkan merge you can use this repo: https://github.com/Ranoller/gddragonbones
To compile with godot 3.1 to 4.0 after vulkan merge use: https://github.com/mauville-technologies/godot-dragonbones (current maintained repo)

Please, is you have a compiling problem, test that you are using the correct repo with the correct version.

**Comment by sanja-sa** [comment]
This repo worked with all version Godot engine from 2.1 to 3.4. It was tested on last stable 3.4 version.
