### ISSUE TITLE
Loading an older dragonbones resource (4_5) in place of a newer format one can sometimes crash godot's editor

### ISSUE THREAD

**Issue by blurymind** [sanja-sa/gddragonbones#7]
older dragonbones files works in godot now!
However they can some times crash the editor. I loaded a 5.6 rooster, then after that loaded the 4_5 dragon example @Ranoller shared and that crashed godot editor.
Here is the terminal output
```
OPENING: F:/stuff/godot/godot/dragonbones (F:::stuff::godot::godot::dragonbones)
running cmdline: "F:\stuff\godot\godot-2.1.4-dbones2.exe" "-path" "F:/stuff/godot/godot/dragonbones" "-editor"
unicode error: invalid skip
DB resource (res://Rooster_Ani/Rooster_Ani_ske.json) loaded in 0 msecs
ERROR: GDDragonBones::set_resource: Null resources
   At: modules\gddragonbones\gddragonbones.cpp:174
DB resource (res://Rooster_Ani/rooster/5_6/Rooster_Ani_ske.json) loaded in 0 msecs
DB resource (res://DragonBonesExport4_5/NewDragon_1_ske.json) loaded in 0 msecs
ERROR: Vector<struct Vector2>::operator []: SEVERE: Index p_index out of size (size()).
   At: d:\build\dbonesgodot\godot-2.1.4-stable\core\vector.h:136
```
[DragonBonesExport4_5.zip](https://github.com/sanja-sa/gddragonbones/files/1669004/DragonBonesExport4_5.zip)
 
[rooster.zip](https://github.com/sanja-sa/gddragonbones/files/1669007/rooster.zip)

**Comment by Ranoller** [comment]
This example is the "import from spine" demo from dragonbones editor. I imported the "cocos example" and works:
![demonbones1](https://user-images.githubusercontent.com/11712737/35460724-497b9c68-02e5-11e8-9d13-1cc6bb698252.gif)



[DragonBonesDemon.zip](https://github.com/sanja-sa/gddragonbones/files/1669184/DragonBonesDemon.zip)

4.0 4.5 and 5.5 files work exactly

**Comment by Ranoller** [comment]
Probably bug is from "dragonbones importer" not from this plugin

Edit: It´s difficult to know if there is some issue with the plugin without do an entire demo animation from "0". I will do one for share, but this take me a bit (no so long :) :) :) ), so don´t try to fix a bug that probably doesn´t exist until we can proof that.

Edit2: It will be fine to test that with an animation from CoaTools from blender, to see if there is issues from that (I do not work with this plugin)

**Comment by blurymind** [comment]
Coa_tools will need to be updated, but I  am going to give it a test 👍 
Here is the latest version:
https://github.com/ndee85/coa_tools/releases

![coa-tools](https://user-images.githubusercontent.com/6495061/35461690-ceabce1c-02e0-11e8-8c96-f56a8b497ab5.JPG)

**Comment by blurymind** [comment]
Its unfortunately failing to load coa-tools created dragonbones json files - error loading resource.

I will report this at the coa-tools github, as it is an export bug, not related to this runtime

I posted it here:
https://github.com/ndee85/coa_tools/issues/80

**Comment by Ranoller** [comment]
Well... plugin works from animation made from "0" in DragonBones 4.9.5, and works well. Blend works from code, and is too fun to not do "fade out" and see the object become a pablo picasso picture in the time....
If you want to test:
[GoogleShittyBadAnimatedPlant.zip](https://github.com/sanja-sa/gddragonbones/files/1670339/GoogleShittyBadAnimatedPlant.zip)


(I didn´t test signals)

**Comment by blurymind** [comment]
Animations exported from dragonbones 4.9.5  (format 4_5) work fine now!
Animations exported from coa-tools don't work anymore - but @ndee85 is working on fixing that - he is re-writing the dragonbones export functionality, so we will be able to save to the newest dragonbones file type spec with blender in the future.

I can confirm that exporting from 4.9.5 works without internet connection and login- so for now I am going to use that version of the editor.

Btw this issue is about crashing godot's editor by loading different dragonbones files into a db node.
@Ranoller were you able to reproduce the crash?
I might give it a try again and see if I can find out more specific steps to cause it

**Comment by sanja-sa** [comment]
https://github.com/sanja-sa/gddragonbones/commit/8edc00281c54df68594f53357171cd54b75cac49

**Comment by blurymind** [comment]
@sanja-sa I tried to crash it and seems rock solid now! This bug is squashed now, so closing this

Thank you for the fix. One stone, two bugs down
