### ISSUE TITLE
Godot 3 crash on save when a scene have an empty DragonBones node 

### ISSUE THREAD

**Issue by Ranoller** [sanja-sa/gddragonbones#9]
You can save the scene if a texture and a skeleton is in the node. Empty node closes godot and is not saved.

Edit: crashes godot 2.1.4 too.

**Comment by sanja-sa** [comment]
https://github.com/sanja-sa/gddragonbones/commit/b3115c3fa571e8e7aafafb5457ab091931e4d1a1

**Comment by Ranoller** [comment]
I can´t compile today, i will test tomorrow.

**Comment by Ranoller** [comment]
Tested... and fixed, thanks.
